# Generated by Django 4.2.1 on 2023-06-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('CoaId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=60, null=True)),
                ('Surname', models.CharField(max_length=60, null=True)),
                ('Contact', models.CharField(max_length=10, null=True)),
                ('Emailid', models.CharField(max_length=60, null=True)),
                ('Age', models.CharField(max_length=40, null=True)),
                ('Gender', models.CharField(max_length=10, null=True)),
                ('JobTitle', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('MemId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=60, null=True)),
                ('Surname', models.CharField(max_length=60, null=True)),
                ('Contact', models.CharField(max_length=10, null=True)),
                ('Emailid', models.CharField(default='example@example.com', max_length=60)),
                ('Age', models.CharField(max_length=40, null=True)),
                ('Gender', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('NameId', models.CharField(default='', max_length=60, primary_key=True, serialize=False)),
                ('Amount', models.CharField(max_length=40, null=True)),
                ('Duration', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Joindate', models.DateField()),
                ('Expdate', models.DateField()),
                ('State', models.CharField(max_length=20, null=True)),
                ('CoachId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.coach')),
                ('MemberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.member')),
                ('PlanIdName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.plan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='memberplan',
            constraint=models.UniqueConstraint(fields=('MemberId', 'PlanIdName'), name='unique_member_plan'),
        ),
    ]
